// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt8wCPEqLpYmC_m14BVBKqfghy-DdFWsU',
    appId: '1:506910508131:web:6d4aef7f46b22da689e456',
    messagingSenderId: '506910508131',
    projectId: 'fir-practice-e489d',
    authDomain: 'fir-practice-e489d.firebaseapp.com',
    storageBucket: 'fir-practice-e489d.appspot.com',
    measurementId: 'G-T39P29551E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZVJOsXsdCpCCCwUbDGBnisxl9zrd3mDw',
    appId: '1:506910508131:android:9bfeab2e2b9601de89e456',
    messagingSenderId: '506910508131',
    projectId: 'fir-practice-e489d',
    storageBucket: 'fir-practice-e489d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDsyiQY4yUoJsdRj6anLSo9d0xtVuW0Mc',
    appId: '1:506910508131:ios:e185e1cb4663885f89e456',
    messagingSenderId: '506910508131',
    projectId: 'fir-practice-e489d',
    storageBucket: 'fir-practice-e489d.appspot.com',
    iosClientId:
        '506910508131-bqcmmn3gt91b5kj2htniuujpkqfat114.apps.googleusercontent.com',
    iosBundleId: 'com.example.app1',
  );
}
